---
- name: Print "Hello World"
  hosts: localhost
  tasks:
    - name: Print "Hello World"
      set_fact:
        random: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
    - debug:
        var: random
    - name: Templating
      template:
        src: ./files/random_string.j2
        dest: ./random_string.txt


